
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333 
      - OLLAMA_URL=http://host.docker.internal:11434
      - QDRANT_COLLECTION_NAME=profiles
      - VECTOR_SIZE=312
      - MODEL_NAME=gemma4:e4b
      - VECTORIZER_MODEL_NAME=cointegrated/rubert-tiny2